import "./globals.css"
import Navbar from "./navbar"
import Providers from "./Providers"
import { cookies } from "next/headers"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  // Read the cookies on the server
  const cookieStore = cookies()
  const token = cookieStore.get("jwt_token")?.value

  // Determine if the user is authenticated
  const isAuthenticated = token ? true : false

  return (
    <html lang="en">
      <body>
        <Providers isAuthenticated={isAuthenticated}>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
